# This workflow builds and publishes Python packages to PyPI when a release tag is pushed
# and all tests pass

name: build and release

on:
  workflow_run:
    workflows: ["linux-test", "windows-test"]
    types:
      - completed

jobs:
  build:
    # Only run if:
    # 1. The triggering workflow succeeded
    # 2. The triggering workflow was run on a release_* tag
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      startsWith(github.event.workflow_run.head_branch, 'release_')
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Show workflow run info
        run: |
          echo "Workflow: ${{ github.event.workflow_run.name }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Event: ${{ github.event.workflow_run.event }}"
          echo "Head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Head SHA: ${{ github.event.workflow_run.head_sha }}"

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.3.3/install.sh | sh

      - name: Install dependencies with uv
        run: |
          uv sync --all-extras --dev

      - name: Build with uv (both sdist and wheel)
        run: uv run python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-packages-${{ github.event.workflow_run.head_branch }}
          path: ./dist/
          if-no-files-found: error
          retention-days: 5

  publish:
    name: Publish to PyPI
    permissions:
      id-token: write
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-packages-${{ github.event.workflow_run.head_branch }}
          path: ./dist/

      - name: List distributions to upload
        run: ls -lh ./dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
