# This workflow builds and publishes Python packages to PyPI when a release is created

name: build and release

on:
  push:
    tags: release*
  workflow_run:
    workflows: ["linux-test", "windows-test"]
    types:
      - completed

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/release')
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Set up uv
        # Install uv version 0.3.3 using the installer
        run: curl -LsSf https://astral.sh/uv/0.3.3/install.sh | sh
      - name: Install dependencies with uv
        run: |
          uv sync --all-extras --dev
      - name: build with uv
        run: uv run python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist
          if-no-files-found: error
          overwrite: true

  publish:
    if: startsWith(github.ref, 'refs/tags/release')
    name: Publish to PyPI
    environment: release
    permissions:
      id-token: write
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
