# This workflow will install Python dependencies, run tests and lint with a variety of Python versions on macOS
# For more information see: https://docs.astral.sh/uv/guides/integration/github/

name: macos-test

on:
  push:
    branches: ["main"]
    tags:
      - "release_*"
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t"]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.5"
          enable-cache: true

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Lint with Ruff
        run: uv run ruff check --output-format=github src
        continue-on-error: true

      - name: Test with pytest
        run: uv run pytest
        # Note: On Python 3.14+, test_shared_client_connection_pooling is expected to fail (xfail)
        # due to httpcore 1.1.x incompatibility with Python 3.14's typing.Union
        # This is an upstream issue that will be resolved in httpcore 1.2.0+
