# This workflow will install Python dependencies, run tests and lint with a variety of Python versions on windows
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: windows-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: [windows-latest]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pytest
          pip install -r requirements.txt
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github src
        continue-on-error: true
      - name: Test with pytest
        run: |
          pytest
