# This workflow will install Python dependencies, run tests and lint with a variety of Python versions on windows
# For more information see: https://docs.astral.sh/uv/guides/integration/github/

name: windows-test

on:
  push:
    branches: ["main"]
    tags:
      - "release_*"
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t"]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.5"
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Lint with Ruff
        run: uv run ruff check --output-format=github src
        continue-on-error: true

      - name: Test with pytest
        run: uv run pytest
